version: '3.8'
services:
  db-test:
    container_name: challenge_db
    image: postgres:11.5
    restart: always
    env_file: ./.env.test
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_PASSWORD
      - POSTGRES_PASSWORD=$DATABASE_NAME
    ports:
      - 5432:5432
    expose:
      - 5432
